### ISSUE TITLE
suggestion: fix design secondary color for landing page

### ISSUE THREAD

**Issue by mikdadayan** [mikdadayan/vit-standalone#1]
```css
button {
  font: inherit;
  cursor: pointer;
  background-color: #c28815;
  color: #292d2d;
  padding: 0.25rem 1rem;
  border-radius: 4px;
  border: 1px solid #f8bd47;
}
```
